# uniortho completion                                      -*- shell-script -*-

# This bash completions script was generated by
# completely (https://github.com/dannyben/completely)
# Modifying it manually is not recommended

_uniortho_completions_filter() {
  local words="$1"
  local cur=${COMP_WORDS[COMP_CWORD]}
  local result=()

  if [[ "${cur:0:1}" == "-" ]]; then
    echo "$words"
  
  else
    for word in $words; do
      [[ "${word:0:1}" != "-" ]] && result+=("$word")
    done

    echo "${result[*]}"

  fi
}

_uniortho_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")
  local compline="${compwords[*]}"

  case "$compline" in
    'run'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_uniortho_completions_filter "--ani --completeness --contamination --gtdb_version_url --help --input_files --outfolder --threads -C -a -c -g -h -i -o -t")" -- "$cur" )
      ;;

    'r'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_uniortho_completions_filter "--ani --completeness --contamination --gtdb_version_url --help --input_files --outfolder --threads -C -a -c -g -h -i -o -t")" -- "$cur" )
      ;;

    *)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_uniortho_completions_filter "--help --version -h -v r run")" -- "$cur" )
      ;;

  esac
} &&
complete -F _uniortho_completions uniortho

# ex: filetype=sh
